### ISSUE TITLE
Redis installation fails

### ISSUE THREAD

**Issue by spinningarrow** [mjhea0/node-docker-workflow#5]
I was following the guide here: http://mherman.org/blog/2015/03/06/node-with-docker-continuous-integration-and-delivery/ but somehow I can't get things working.

After installing `docker-compose`, when I do `docker-compose up` I get this:

```
Creating nodedockerworkflow_redis_1...
Building redis...
Step 0 : FROM dockerfile/ubuntu
Pulling repository dockerfile/ubuntu
Service 'redis' failed to build: Error: image dockerfile/ubuntu:latest not found
```

I tried modifying the Dockerfile inside the redis directory, changing `FROM dockerfile/ubuntu` to `FROM ubuntu` but that failed with a different error.

Any idea what's going on?

**Comment by mjhea0** [comment]
I just updated the dockerfile. It should work now.

Also, if you keep having problems, it can help to stop then start boot2docker.

``` sh
$ boot2docker stop
$ boot2docker start
```

**Comment by spinningarrow** [comment]
Great. Thanks!

**Comment by mjhea0** [comment]
Just updated the [blog post](http://mherman.org/blog/2015/03/06/node-with-docker-continuous-integration-and-delivery) as well. Cheers!
